let petersHouselengthInMeter = 8 ;
let petersHousedepthInMeter = 10;
let petesrHousewidthInMeyer = 10;
let volumeOfPetersHouseInMeter = petersHouselengthInMeter*petersHousedepthInMeter*petesrHousewidthInMeyer;
 let petersHouseGardenSizeInM2 = 100;
 let house1cost = 2500000;
 let houseprice = volumeOfPetersHouseInMeter * 2.5 * 1000 + petersHouseGardenSizeInM2 * 300;
 console.log("Peter paying $" +  (house1cost-houseprice) + " lower price");
 let juliasHouselengthInMeter = 8;
let juliaHousedepthInMeter = 11;
let juliasHousewidthInMeter = 5;
let volumeOfjuliasHouseInMeter = juliasHouselengthInMeter*juliaHousedepthInMeter*juliasHousewidthInMeter;
 let juliasHouseGardenSizeInM2 = 70;
 let houseprice2 = volumeOfjuliasHouseInMeter * 2.5 * 1000 + juliasHouseGardenSizeInM2 * 300;
 let house2cost = 1000000;
console.log("Julia paying $" +  (houseprice2-house2cost) + " higher price");