import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/Navbar";
import { ThemeProvider } from "../context/ThemeContext";
import ThemeToggleButton from "@/Components/ThemeSwitcher";
import { LocalizationProvider } from "../context/LocalizationContext";
import LanguageSwitcher from "@/Components/LanguageSwitcher";
import { CounterProvider } from "@/context/CounterContext";
import CounterComponent from "@/Components/CounterComponent";
import TodoList from "@/Components/TodoList";
import { TodoProvider } from "@/context/TodoContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LocalizationProvider>
          <ThemeProvider>
            <CounterProvider>
              <TodoProvider>
                <Navbar />

                <ThemeToggleButton />
                <LanguageSwitcher />

                <TodoList />

                {children}

                <CounterComponent />
              </TodoProvider>
            </CounterProvider>
          </ThemeProvider>
        </LocalizationProvider>
      </body>
    </html>
  );
}
